# Generated by Django 5.2 on 2025-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_landlord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
