# Generated by Django 5.2 on 2025-06-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
