# Generated by Django 5.2 on 2025-05-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('room', 'Room'), ('flat', 'Flat'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], max_length=20),
        ),
    ]
