# Generated by Django 5.2 on 2025-06-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('room', 'Room'), ('flat', 'Flat'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='main.category'),
        ),
    ]
