# Generated by Django 5.2 on 2025-06-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_category_name_alter_property_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='property',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='main.category'),
        ),
    ]
