# Generated by Django 5.2 on 2025-06-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_inquiry_property_inquiry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.property'),
        ),
    ]
