# Generated by Django 5.2 on 2025-06-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifthomerequest',
            old_name='message',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='shifthomerequest',
            old_name='current_address',
            new_name='from_location',
        ),
        migrations.RenameField(
            model_name='shifthomerequest',
            old_name='date_of_shift',
            new_name='shifting_date',
        ),
        migrations.RenameField(
            model_name='shifthomerequest',
            old_name='new_address',
            new_name='to_location',
        ),
        migrations.RemoveField(
            model_name='shifthomerequest',
            name='user',
        ),
        migrations.AddField(
            model_name='shifthomerequest',
            name='name',
            field=models.CharField(default='Unnamed request', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifthomerequest',
            name='phone',
            field=models.CharField(default='unnamed request', max_length=15),
            preserve_default=False,
        ),
    ]
