# Generated by Django 5.2 on 2025-06-14 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_message_shifthomerequest_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FindMeRoomRequest',
            new_name='FindMeRoom',
        ),
        migrations.RenameModel(
            old_name='ShiftHomeRequest',
            new_name='ShiftHome',
        ),
    ]
