# Generated by Django 5.2 on 2025-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_findmeroomrequest_findmeroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifthome',
            old_name='details',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='shifthome',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shifthome',
            name='shifting_date',
        ),
        migrations.AddField(
            model_name='shifthome',
            name='beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='chairs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='computer_tables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='cookware',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='cupboards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='deposit_slip',
            field=models.ImageField(blank=True, null=True, upload_to='deposits/'),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='dining_tables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='dressing_tables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='email',
            field=models.EmailField(default='Default Name', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifthome',
            name='flower_pots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='from_floor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='gas_cylinders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='heaters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='kitchen_racks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='mattresses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='property_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial')], default='Unnamed Request', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifthome',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='refrigerator',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='shoe_racks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='sofas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='table_fans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='table_lamps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='tea_tables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='to_floor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='tvs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='when',
            field=models.CharField(choices=[('Instant', 'Instant Booking'), ('Later', 'Schedule for Later')], default='Unnamed Request', max_length=10),
            preserve_default=False,
        ),
    ]
