# Generated by Django 5.2 on 2025-06-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_shifthome_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifthome',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
