# Generated by Django 5.2 on 2025-06-19 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_shifthome_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='findmeroom',
            old_name='created_at',
            new_name='date_requested',
        ),
        migrations.RenameField(
            model_name='findmeroom',
            old_name='location_preference',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='findmeroom',
            name='budget',
        ),
        migrations.AddField(
            model_name='findmeroom',
            name='category',
            field=models.CharField(choices=[('Room', 'Room'), ('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='findmeroom',
            name='price_max',
            field=models.PositiveIntegerField(default=12355),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='findmeroom',
            name='price_min',
            field=models.PositiveIntegerField(default=123344),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='findmeroom',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
