# Generated by Django 5.2 on 2025-06-19 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_date_requested_findmeroom_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='findmeroom',
            name='deposit_slip',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='find_me_room/deposit_slips/'),
            preserve_default=False,
        ),
    ]
