# Generated by Django 5.2 on 2025-06-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_findmeroom_deposit_slip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifthome',
            name='qr_code',
        ),
    ]
