# Generated by Django 5.2 on 2025-06-19 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_shifthome_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifthome',
            name='deposit_slip',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='deposits/'),
            preserve_default=False,
        ),
    ]
