# Generated by Django 5.2 on 2025-06-19 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_shifthome_deposit_slip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='tenant',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='main.property'),
            preserve_default=False,
        ),
    ]
