# Generated by Django 5.2 on 2025-06-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_timestamp_inquiry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findmeroom',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
