# Generated by Django 5.2 on 2025-06-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
